/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TreeOfWealth } from "./TreeOfWealth";

export { TreeOfWealth__factory } from "./factories/TreeOfWealth__factory";
